backend:
  name: git-gateway
  repo: LatiefAkbar/geowisata-desa-karangsambung
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/id-situs-anda-dari-decapbridge/pkce
  auth_token_endpoint: /sites/id-situs-anda-dari-decapbridge/token
  gateway_url: https://gateway.decapbridge.com

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Penulis", name: "penulis", widget: "string" }
      - { label: "Kategori", name: "kategori", widget: "string" }
      - { label: "Foto Sampul (URL)", name: "foto_sampul", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
